global_config:
  seed: 5959
  device: "cpu"
  is_mp: False
---
data_config:
  data_path: "./data/"
  dataset_name: "MNIST"
  # 9 class , shard_size 5
  # 6 class , shard_size 7
  # 2 class , shard_size 22
  num_shards: 200
  shard_size: 22
  contained_num_class: 2
  iid: False #is not iid
---
fed_config:
  #C: 0.1
  K: 30
  R: 40
  E: 10
  B: 16
  criterion: torch.nn.CrossEntropyLoss
  optimizer: torch.optim.SGD
---
optim_config:
  lr: 0.01
  momentum: 0.9
---
init_config:
  init_type: "xavier"
  init_gain: 1.0
  gpu_ids: [0, 1, 2]
---
model_config: 
  #name: TwoNN
  #in_features: 784
  #num_hiddens: 200
  #num_classes: 10
  
  name: CNN
  in_channels: 1
  hidden_channels: 32
  num_hiddens: 512
  num_classes: 10
---
log_config:
  log_path: "./log/"
  log_name:  "FL.log"
  tb_port: 5252
  tb_host: "0.0.0.0"
